import re

filepath = r"C:\Users\34598\Doubao\chats\2026-08-31\new-chat\ict-prep-app\src\data\quizzes.ts"

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

questions = '''
  { id: 'dc-141', type: 'single', question: 'OSPF中，Hello报文的默认发送间隔在广播网络中是多少？', options: ['5秒', '10秒', '30秒', '60秒'], answer: '10秒', explanation: 'OSPF Hello报文默认发送间隔：广播网络（Broadcast）和点到点网络（P2P）为10秒，NBMA和点到多点网络为30秒。死亡时间（Dead Interval）默认是Hello间隔的4倍：广播/P2P为40秒，NBMA/P2MP为120秒。Hello报文用于发现邻居、维护邻居关系（Keepalive）、选举DR/BDR、协商参数（区域ID、认证、掩码、Hello间隔、死亡间隔等）。如果在死亡时间内未收到邻居的Hello报文，则认为邻居失效，拆除邻居关系。Hello间隔和死亡时间可在接口上通过ospf timer hello和ospf timer dead命令修改，但邻居两端必须一致才能建立邻居。', knowledgeId: 'datacom-ospf', direction: 'datacom' },
  { id: 'dc-142', type: 'single', question: 'BGP中，Origin属性为IGP表示什么？', options: ['路由通过import-route引入', '路由通过network命令注入或IGP学习', '路由通过EGP学习', '路由来源未知'], answer: '路由通过network命令注入或IGP学习', explanation: 'BGP Origin（起源）属性标识路由的来源，有三种类型：1.IGP（i）：路由通过network命令注入BGP，或从IGP（OSPF/IS-IS等）学习，优先级最高（最可信）。2.EGP（e）：路由通过EGP（外部网关协议，已淘汰）学习，优先级次之。3.Incomplete（?）：路由通过import-route（引入）方式注入BGP，或来源未知，优先级最低。Origin优选顺序：IGP > EGP > Incomplete。Origin是BGP公认必遵属性（Well-known Mandatory），所有BGP更新必须包含。Origin属性影响BGP路由优选（第5条规则，在Weight、Local_Pref、本地始发、AS_Path之后比较）。通常通过network命令注入的路由Origin为IGP，通过import-route引入的路由Origin为Incomplete。可通过route-policy的apply origin命令修改Origin属性。', knowledgeId: 'datacom-bgp', direction: 'datacom' },
  { id: 'dc-143', type: 'judge', question: 'IS-IS中，NET的NSEL字段值为00表示该地址对应路由器本身。', options: ['正确', '错误'], answer: '正确', explanation: 'NET（Network Entity Title，网络实体标题）是IS-IS中路由器的网络层地址，格式为：Area ID（1-13字节）+ System ID（6字节）+ NSEL（1字节）。NSEL（Network Service Access Point Selector，网络服务接入点选择器）标识网络层服务类型，值为00表示该NET对应路由器本身（IS本身），类似于IP协议号为0。IS-IS中路由器的NET的NSEL必须为00。如果NSEL不为0，则表示主机或特定服务（如CLNP中的传输层协议），不是路由器本身。System ID（系统ID）6字节，唯一标识一个路由器，通常由IP地址转换而来（如192.168.001.001→1921.6800.1001），同一区域内System ID必须唯一。Area ID（区域ID）标识区域，同一Level-1区域内Area ID必须相同。NET长度8-20字节，通常为10字节（Area ID 3字节+System ID 6字节+NSEL 1字节）。一台路由器可配置多个NET（最多3个），但System ID必须相同，Area ID可以不同（用于区域迁移）。', knowledgeId: 'datacom-isis', direction: 'datacom' },
  { id: 'dc-144', type: 'single', question: 'STP中，端口从Blocking到Forwarding需要经过哪些状态？', options: ['Blocking→Listening→Learning→Forwarding', 'Blocking→Learning→Forwarding', 'Blocking→Listening→Forwarding', '直接Forwarding'], answer: 'Blocking→Listening→Learning→Forwarding', explanation: 'STP（802.1D）端口状态：1.Disabled（禁用）：端口被管理性关闭，不参与STP，不转发数据。2.Blocking（阻塞）：端口被STP阻塞，不转发用户数据，不学习MAC地址，只接收BPDU。3.Listening（监听）：端口开始参与STP，接收和发送BPDU，不转发用户数据，不学习MAC地址，持续15秒（Forward Delay）。4.Learning（学习）：端口开始学习MAC地址（构建MAC地址表），但不转发用户数据，持续15秒（Forward Delay）。5.Forwarding（转发）：端口正常转发用户数据，学习MAC地址，发送/接收BPDU。STP端口从Blocking到Forwarding需要经过Listening（15秒）+Learning（15秒）=30秒，收敛慢。RSTP（802.1w）简化为三种状态：Discarding（禁用/阻塞/监听合并）、Learning、Forwarding，通过P/A（Proposal/Agreement）协商机制实现快速收敛（秒级），无需等待30秒。MSTP（802.1s）基于RSTP，端口状态相同。', knowledgeId: 'datacom-stp', direction: 'datacom' },
  { id: 'dc-145', type: 'single', question: 'VLAN中，Trunk端口的PVID作用是？', options: ['标记Trunk端口的VLAN ID，接收无标签帧时打上PVID标签，发送PVID VLAN帧时不打标签', '指定Trunk端口允许通过的VLAN', '指定Trunk端口的 native VLAN，仅用于接收', '指定Trunk端口的管理VLAN'], answer: '标记Trunk端口的VLAN ID，接收无标签帧时打上PVID标签，发送PVID VLAN帧时不打标签', explanation: 'Trunk端口的PVID（Port VLAN ID，端口VLAN ID，默认VLAN 1）作用：1.接收无标签帧（Untagged）时，打上PVID标签，按PVID VLAN处理。2.发送PVID VLAN的帧时，剥离802.1Q标签（不打标签），因为PVID VLAN是本征VLAN（Native VLAN）。3.发送其他允许通过的VLAN帧时，保留802.1Q标签。Trunk端口通过port trunk allow-pass vlan命令指定允许通过的VLAN（默认仅VLAN 1），通过port trunk pvid vlan命令修改PVID（默认1）。Trunk两端的PVID必须一致，否则可能导致VLAN泄漏或通信问题。Access端口的PVID就是其所属VLAN（port default vlan），Access端口发送时始终剥离标签，接收时打上PVID标签。Hybrid端口可灵活配置tagged和untagged列表，PVID是untagged列表中的一个VLAN。802.1Q标签中，PVID VLAN的帧通常不打标签（Native VLAN），这是为了与不支持802.1Q的设备兼容。', knowledgeId: 'datacom-vlan', direction: 'datacom' },
  { id: 'sec-114', type: 'single', question: 'IPSec中，感兴趣流（Interesting Traffic）的作用是？', options: ['定义哪些流量需要IPSec保护', '定义加密算法', '定义认证方式', '定义隧道模式'], answer: '定义哪些流量需要IPSec保护', explanation: '感兴趣流（Interesting Traffic）由ACL定义，用于指定哪些流量需要IPSec保护（加密/认证），哪些流量按普通方式转发。1.匹配感兴趣流的流量：进入IPSec处理，封装为IPSec报文（AH/ESP），通过IPSec隧道转发到对端。2.不匹配感兴趣流的流量：按普通路由方式转发，不经过IPSec处理。感兴趣流在IPSec策略视图下通过security acl命令引用。感兴趣流的方向很重要：源和目的要正确配置（本端子网到对端子网），对端的感兴趣流应该是镜像的（源和目的相反）。感兴趣流可以是一条或多条ACL规则。在策略模板（Template）方式中，对端（动态IP）不配置感兴趣流，由本端定义。感兴趣流也用于决定是否触发IKE协商：当有匹配感兴趣流的流量需要转发时，如果IPSec SA尚未建立，则触发IKE协商建立SA。感兴趣流的粒度影响IPSec SA数量：粗粒度（大网段）SA少，细粒度（主机到主机）SA多，通常建议用粗粒度减少SA数量。', knowledgeId: 'security-ipsec', direction: 'security' },
  { id: 'sec-115', type: 'judge', question: 'SSL VPN的网络扩展模式下，客户端获得虚拟IP后，可以像在企业内网一样访问所有授权资源。', options: ['正确', '错误'], answer: '正确', explanation: 'SSL VPN的网络扩展（Network Extension，也叫全网互联/Full Network Access）模式：1.客户端安装SSL VPN专用客户端软件（如华为SecoClient）。2.客户端与SSL VPN网关（防火墙/AC）建立SSL/TLS隧道。3.网关从虚拟IP地址池中为客户端分配一个虚拟IP地址（内网IP）。4.客户端获得虚拟IP后，可以像在企业内网一样访问所有授权的网络资源（包括Web、FTP、数据库、远程桌面、SSH等所有IP层应用），类似于IPSec VPN的效果。5.网络扩展模式功能最强大，支持所有IP层应用，但需要安装客户端软件。其他SSL VPN接入模式：Web代理（仅Web应用，浏览器即可）、文件共享（仅CIFS/FTP文件访问）、端口转发（仅特定TCP应用，需浏览器插件）。网络扩展模式还支持：路由推送（网关向客户端推送内网路由）、DNS推送（推送内网DNS服务器）、分离隧道（Split Tunnel，仅访问内网的流量走VPN，访问Internet的流量直接走本地，节省带宽）、全隧道（所有流量都走VPN）。SSL VPN相比IPSec VPN的优势：无需客户端（Web代理模式）、穿越NAT/防火墙方便（443端口）、细粒度访问控制、终端安全检查。', knowledgeId: 'security-ssl-vpn', direction: 'security' },
  { id: 'wlan-108', type: 'single', question: 'WLAN中，AP发现AC的方式不包括以下哪种？', options: ['广播方式', 'DHCP Option43', 'DNS方式', 'RADIUS方式'], answer: 'RADIUS方式', explanation: 'FIT AP（瘦AP）发现AC（接入控制器）的方式：1.广播方式（Broadcast）：AP发送CAPWAP Discover广播报文，同二层网络的AC回应，适合AC和AP在同一网段（二层组网）。2.DHCP Option43方式：DHCP服务器在Option43字段中携带AC的IP地址列表，AP从DHCP获取IP时同时获取AC地址，适合跨三层组网，最常用。3.DNS方式：AP通过解析特定域名（如hwac.com，可配置）获取AC IP地址，需DNS服务器配置对应记录。4.静态配置方式：在AP上手动配置AC IP地址（通过AP命令行或Web界面），适合固定环境。RADIUS是认证协议，用于用户认证和计费，不是AP发现AC的方式。AP发现AC后，建立CAPWAP控制隧道（UDP 5246，DTLS加密），然后下载版本和配置，最后正常工作。AP上线流程：获取IP→发现AC→建立CAPWAP控制隧道→下载版本→下载配置→正常工作。如果AP发现多个AC，会选择优先级最高的AC（可配置AC优先级），实现AC负载分担和冗余备份。', knowledgeId: 'wlan-arch', direction: 'wlan' },
  { id: 'dcn-106', type: 'judge', question: 'VXLAN头端复制（Head End Replication）方式下，VTEP将BUM流量复制多份单播发送给所有同VNI的VTEP。', options: ['正确', '错误'], answer: '正确', explanation: 'VXLAN中BUM流量（Broadcast广播、Unknown unicast未知单播、Multicast组播）的处理方式有两种：1.头端复制（Head End Replication，HER）：VTEP收到BUM流量后，将报文复制多份，分别单播发送给所有属于同一VNI的远端VTEP（基于头端复制列表，通过EVPN Type 3路由或静态配置学习）。优点：简单，不需要underlay网络支持组播；缺点：VTEP数量多时复制开销大，带宽浪费（重复发送多份相同报文）。2.组播（Multicast）：利用underlay三层网络的组播树（PIM等）分发BUM流量，每个VNI映射到一个组播组，VTEP加入对应组播组，BUM流量通过组播树分发。优点：效率高（网络自动复制，不重复发送）；缺点：需要underlay支持组播，配置复杂。头端复制是小规模VXLAN部署的常用方式，大规模部署推荐用组播或EVPN+头端复制（EVPN自动维护头端复制列表，减少配置）。EVPN环境下，通常用头端复制（因为数据中心underlay通常不启用组播，用BGP EVPN代替），通过EVPN Type 3路由（Inclusive Multicast Ethernet Tag Route）自动发现VTEP并构建头端复制列表。头端复制列表包含所有同VNI的远端VTEP IP地址。', knowledgeId: 'dcn-vxlan-basic', direction: 'dcn' },
  { id: 'dc-146', type: 'single', question: '静态路由中，永久静态路由（Permanent Static Route）的特点是？', options: ['出接口down时仍保留在路由表中', '出接口down时从路由表中删除', '优先级最高', '不可删除'], answer: '出接口down时仍保留在路由表中', explanation: '永久静态路由（Permanent Static Route，也叫永久路由）：配置了permanent参数的静态路由，即使出接口down（物理/协议状态down），该路由仍然保留在路由表中（不被删除）。普通静态路由（未配置permanent）：当出接口down时，路由会从路由表中撤销（因为下一跳不可达）。永久静态路由的应用场景：1.出接口状态不稳定，但希望路由始终存在（如拨号接口，按需拨号，接口平时down但有流量时up）。2.需要路由始终存在以触发特定操作（如触发拨号）。3.避免路由频繁震荡（接口频繁up/down导致路由频繁增删）。永久静态路由的注意事项：如果出接口确实故障且无法恢复，永久静态路由仍在路由表中，可能导致流量被丢弃（因为出接口down无法转发），所以需要谨慎使用。静态路由其他特性：优先级默认60（可通过preference参数修改）、支持迭代（下一跳非直连时递归查找最终下一跳）、支持浮动静态路由（高优先级备份）、支持默认路由（0.0.0.0/0）、支持黑洞路由（Null0接口，丢弃匹配流量，用于防环路或流量过滤）。', knowledgeId: 'datacom-static-route', direction: 'datacom' },
'''

pattern = r'\n  // ==================== 自动更新题库 Batch 1'
replacement = questions + '\n  // ==================== 自动更新题库 Batch 1'

new_content, count = re.subn(pattern, replacement, content, count=1)

if count > 0:
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Inserted {questions.count('id:')} questions successfully")
else:
    print("Pattern not found!")
