import re

filepath = r"C:\Users\34598\Doubao\chats\2026-08-31\new-chat\ict-prep-app\src\data\quizzes.ts"

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

questions = '''
  // ==================== 扩充题库 Batch B ====================
  {
    id: 'dc-b001',
    type: 'single',
    question: 'OSPF中，完全末梢区域（Totally Stub Area）不接收哪种LSA？',
    options: ['Type 1和Type 2', 'Type 3（除默认路由）、Type 4、Type 5', 'Type 7', '仅Type 5'],
    answer: 'Type 3（除默认路由）、Type 4、Type 5',
    explanation: 'Totally Stub（完全末梢区域）是最严格的末梢区域，不接收Type 3区域间路由（除ABR生成的默认路由0.0.0.0/0）、Type 4（ASBR位置）、Type 5（外部路由），只接收Type 1/2（本区域内）和默认Type 3。大幅减少LSA数量和路由表规模。',
    knowledgeId: 'datacom-ospf',
    direction: 'datacom',
  },
  {
    id: 'dc-b002',
    type: 'single',
    question: 'BGP中，团体属性Community的作用是？',
    options: ['标记一组路由，便于策略控制', '加密路由', '选择最优路由', '防止环路'],
    answer: '标记一组路由，便于策略控制',
    explanation: 'Community（团体属性）是BGP可选过渡属性，32位，用于标记一组具有相同策略的路由，便于批量控制（如根据Community设置Local_Pref、MED、过滤等）。分为公认团体（No_Export、No_Advertise、Internet、Local_AS）和私有团体（AS:NN格式）。',
    knowledgeId: 'datacom-bgp',
    direction: 'datacom',
  },
  {
    id: 'dc-b003',
    type: 'judge',
    question: 'IS-IS中，L1路由器只能与同区域的路由器建立邻居，不知道其他区域的具体路由。',
    options: ['正确', '错误'],
    answer: '正确',
    explanation: 'IS-IS Level-1（L1）路由器只维护L1链路状态数据库，只能与同区域的L1/L1-2建立邻居，只知道本区域内拓扑，不知道其他区域具体路由。访问其他区域时通过本区域L1/2路由器（ATT位）生成默认路由转发，类似OSPF Stub区域。',
    knowledgeId: 'datacom-isis',
    direction: 'datacom',
  },
  {
    id: 'dc-b004',
    type: 'single',
    question: 'RSTP相比STP的主要改进是？',
    options: ['增加了VLAN支持', '通过P/A协商和边缘端口实现快速收敛（秒级）', '支持加密', '支持IPv6'],
    answer: '通过P/A协商和边缘端口实现快速收敛（秒级）',
    explanation: 'RSTP（802.1w）相比STP（802.1D）的改进：1.P/A（Proposal/Agreement）协商机制，点到点链路上端口快速进入Forwarding，无需等30秒。2.边缘端口（Edge Port）直接Forwarding。3.替代/备份端口快速切换。4.BPDU超时从20秒缩短到6秒（3倍Hello）。5.端口状态简化为Discarding/Learning/Forwarding。RSTP兼容STP。',
    knowledgeId: 'datacom-stp',
    direction: 'datacom',
  },
  {
    id: 'dc-b005',
    type: 'single',
    question: '以下关于VLAN的说法，错误的是？',
    options: ['VLAN隔离广播域', '不同VLAN默认不能直接通信', 'VLAN ID范围1-4094', 'Trunk端口只能属于一个VLAN'],
    answer: 'Trunk端口只能属于一个VLAN',
    explanation: 'Trunk端口可以允许多个VLAN通过（port trunk allow-pass vlan），通过802.1Q标签区分不同VLAN的流量。Access端口只能属于一个VLAN（port default vlan）。VLAN隔离广播域，不同VLAN默认二层隔离，需三层设备（路由器/三层交换机SVI）才能通信。VLAN ID 12位，可用1-4094。',
    knowledgeId: 'datacom-vlan',
    direction: 'datacom',
  },
  {
    id: 'sec-b001',
    type: 'single',
    question: '防火墙安全区域中，以下哪个区域的安全级别最高？',
    options: ['Untrust（5）', 'DMZ（50）', 'Trust（85）', 'Local（100）'],
    answer: 'Local（100）',
    explanation: '华为防火墙安全区域及默认安全级别：Local（100，防火墙本身）> Trust（85，内网可信区域）> DMZ（50，隔离区，放置服务器）> Untrust（5，外网不可信区域）。安全级别数值越大越可信。数据从高级别到低级别为出方向（Outbound），从低级别到高级别为入方向（Inbound）。同区域内流量默认允许，不同区域间流量需安全策略允许。',
    knowledgeId: 'security-firewall-basic',
    direction: 'security',
  },
  {
    id: 'sec-b002',
    type: 'single',
    question: 'IPSec中，ESP协议的IP协议号是？',
    options: ['50', '51', '47', '89'],
    answer: '50',
    explanation: 'IPSec两个协议：ESP（Encapsulating Security Payload，封装安全载荷）IP协议号50，提供加密+认证，是主流；AH（Authentication Header，认证头）IP协议号51，仅提供认证和完整性，不加密，不支持NAT。GRE协议号47，OSPF协议号89。ESP支持传输模式和隧道模式，隧道模式用于VPN（新增外部IP头），传输模式用于主机到主机。',
    knowledgeId: 'security-ipsec',
    direction: 'security',
  },
  {
    id: 'sec-b003',
    type: 'judge',
    question: 'DDoS攻击中，SYN Flood利用TCP三次握手的缺陷，发送大量SYN报文但不回应ACK，耗尽服务器半连接队列。',
    options: ['正确', '错误'],
    answer: '正确',
    explanation: 'SYN Flood是最常见的DDoS攻击之一：攻击者发送大量伪造源IP的SYN报文，服务器回复SYN+ACK后等待ACK（半连接状态），攻击者不回应ACK，服务器半连接队列被占满，无法接受新的正常连接。防御方法：SYN Cookie（不分配半连接资源，用Cookie验证）、增大半连接队列、缩短超时时间、源IP验证、流量清洗、防火墙代理等。其他DDoS攻击：UDP Flood、ICMP Flood（Ping of Death/Smurf）、HTTP Flood（CC攻击）、DNS Query Flood、NTP反射放大攻击、SSDP反射攻击等。',
    knowledgeId: 'security-attack-defense',
    direction: 'security',
  },
  {
    id: 'sec-b004',
    type: 'single',
    question: '以下哪个不是对称加密算法？',
    options: ['AES', 'DES', 'RSA', 'SM4'],
    answer: 'RSA',
    explanation: '对称加密算法：加密和解密使用相同密钥，速度快，适合大量数据加密。常见：AES（128/192/256位，当前主流）、DES（56位，已不安全）、3DES（三重DES，112/168位）、SM4（中国国密，128位）、Blowfish、RC4等。非对称加密算法（公钥加密）：加密和解密使用不同密钥（公钥加密私钥解密，或私钥签名公钥验证），速度慢，适合密钥交换和数字签名。常见：RSA（1024/2048/4096位）、ECC（椭圆曲线，密钥短安全性高）、SM2（中国国密椭圆曲线）、DSA（数字签名）、DH（Diffie-Hellman密钥交换）。混合加密：用非对称加密交换对称密钥，用对称加密传输数据（如HTTPS/TLS、IPSec IKE）。',
    knowledgeId: 'security-crypto',
    direction: 'security',
  },
  {
    id: 'wlan-b001',
    type: 'single',
    question: 'Wi-Fi 6（802.11ax）相比Wi-Fi 5的关键技术不包括？',
    options: ['OFDMA（正交频分多址）', 'MU-MIMO（上下行均支持）', '1024-QAM', '波束成形（Beamforming）'],
    answer: '波束成形（Beamforming）',
    explanation: 'Wi-Fi 6（802.11ax）关键技术：1.OFDMA（正交频分多址）：将信道划分为多个子信道（RU），同时与多个用户通信，提高多用户效率，降低延迟。2.上下行MU-MIMO：Wi-Fi 5只支持下行MU-MIMO，Wi-Fi 6支持上下行均支持，最多8个空间流。3.1024-QAM：相比Wi-Fi 5的256-QAM，调制密度提高25%，单用户速率提升。4.BSS Coloring（BSS着色）：标记不同BSS，减少同频干扰，提高密集环境性能。5.TWT（Target Wake Time，目标唤醒时间）：设备协商唤醒时间，降低功耗，延长电池寿命。波束成形（Beamforming）在Wi-Fi 5（802.11ac）就已支持（802.11n开始有），不是Wi-Fi 6独有。Wi-Fi 6E扩展到6GHz频段。Wi-Fi 7（802.11be）支持320MHz带宽、4096-QAM、16x16 MU-MIMO、多链路操作（MLO）。',
    knowledgeId: 'wlan-wifi6',
    direction: 'wlan',
  },
  {
    id: 'wlan-b002',
    type: 'judge',
    question: 'FIT AP（瘦AP）架构中，AP负责射频管理和数据转发，AC负责配置管理和用户认证。',
    options: ['正确', '错误'],
    answer: '正确',
    explanation: 'FIT AP（瘦AP，也叫集中式架构）：AC（Access Controller，接入控制器）集中管理所有AP，负责配置下发、固件升级、用户认证、漫游管理、安全策略等。AP（Access Point，接入点）负责射频管理（信道/功率调整）、数据加密/解密、数据转发（直接转发或隧道转发）、无线接入等。AP发现AC的方式：广播、DHCP Option43、DNS、静态配置。AP通过CAPWAP协议（控制隧道UDP 5246，数据隧道UDP 5247）与AC通信。FIT AP优势：集中管理、统一配置、快速部署、无缝漫游、负载均衡、安全策略统一。FAT AP（胖AP，自治式架构）：每台AP独立配置和管理，适合小型环境，无法集中管理和无缝漫游。云管理AP（云AP）：通过云平台管理，结合FIT和FAT优势，适合中小企业和分布式部署。',
    knowledgeId: 'wlan-arch',
    direction: 'wlan',
  },
  {
    id: 'dcn-b001',
    type: 'single',
    question: '数据中心Spine-Leaf架构中，Leaf交换机的作用是？',
    options: ['核心交换，连接所有Leaf', '接入服务器，同时连接所有Spine', '存储数据', '管理服务器'],
    answer: '接入服务器，同时连接所有Spine',
    explanation: 'Spine-Leaf（叶脊）架构：1.Leaf（叶节点，接入交换机）：连接服务器（TOR，Top of Rack，柜顶交换机），同时连接到所有Spine节点，是服务器的网关。2.Spine（脊节点，核心交换机）：不连接服务器，只连接所有Leaf节点，提供高带宽的东西向交换。任意两台服务器通信路径：服务器→Leaf→Spine→Leaf→服务器，固定2跳，延迟低且可预测。通过ECMP等价多路径负载分担，充分利用所有Spine链路带宽，实现无阻塞。水平扩展：增加Leaf提高接入密度，增加Spine提高东西向带宽。Spine-Leaf是数据中心网络标准架构，适合东西向流量为主的数据中心（分布式计算、存储、微服务）。underlay通常运行BGP或OSPF/IS-IS，overlay通常用VXLAN/EVPN。',
    knowledgeId: 'dcn-arch',
    direction: 'dcn',
  },
  {
    id: 'dcn-b002',
    type: 'judge',
    question: 'VXLAN通过MAC-in-UDP封装，在三层IP网络上构建大二层虚拟网络，支持约1600万个VNI。',
    options: ['正确', '错误'],
    answer: '正确',
    explanation: 'VXLAN（Virtual Extensible LAN，虚拟可扩展局域网，RFC 7348）：1.封装方式：MAC-in-UDP，将原始以太网帧封装在UDP报文中，外层IP头使用VTEP IP，目的端口UDP 4789。2.VNI（VXLAN Network Identifier）24位，支持约1600万个网段（2^24），远多于VLAN的4094个。3.VTEP（VXLAN Tunnel End Point，VXLAN隧道端点）：负责VXLAN封装和解封装，可在物理交换机、虚拟交换机（vSwitch）、服务器网卡上实现。4.在三层underlay网络上构建二层overlay网络，实现大二层扩展，支持虚拟机迁移（IP不变）。5.解决VLAN数量不足、STP无法支撑大规模二层、多租户隔离等问题。VXLAN通常与EVPN配合（EVPN作为控制面，VXLAN作为数据面），通过EVPN Type 2路由同步MAC/IP，Type 3路由发现VTEP（头端复制），实现自动化和可扩展。BUM流量处理：头端复制（HER）或组播。',
    knowledgeId: 'dcn-vxlan-basic',
    direction: 'dcn',
  },
  {
    id: 'dc-b006',
    type: 'single',
    question: 'IPv6地址2001:0db8:0000:0000:0000:ff00:0042:8329可以简写为？',
    options: ['2001:db8::ff00:42:8329', '2001:db8:0:0:0:ff00:42:8329', '2001:db8::42:8329', '2001:0db8::ff00:0042:8329'],
    answer: '2001:db8::ff00:42:8329',
    explanation: 'IPv6地址简写规则：1.每个16位段中的前导零可以省略（0db8→db8，0000→0，0042→42）。2.连续的全零段可以用::代替，但::在一个地址中只能使用一次（否则无法确定每个::代表多少个零段）。2001:0db8:0000:0000:0000:ff00:0042:8329：省略前导零→2001:db8:0:0:0:ff00:42:8329；连续三个全零段用::代替→2001:db8::ff00:42:8329。注意：::只能用一次，所以不能同时省略开头和结尾的零。IPv6地址128位，8个16位段，用冒号分隔。环回地址::1（0:0:0:0:0:0:0:1），未指定地址::（全零），链路本地地址FE80::/10，唯一本地地址FC00::/7（类似IPv4私有地址），组播地址FF00::/8，任播地址（与单播格式相同，通过配置标识）。IPv6无状态自动配置（SLAAC）：主机根据RA报文的前缀+EUI-64接口标识自动生成全球单播地址，无需DHCPv6。',
    knowledgeId: 'datacom-ipv6-basic',
    direction: 'datacom',
  },
  {
    id: 'dc-b007',
    type: 'single',
    question: 'QoS中，以下哪种队列调度算法可以保证低延迟业务优先？',
    options: ['FIFO（先进先出）', 'PQ（优先级队列）', 'WRR（加权轮询）', 'WFQ（加权公平队列）'],
    answer: 'PQ（优先级队列）',
    explanation: 'QoS队列调度算法：1.PQ（Priority Queuing，优先级队列）：严格按优先级调度，高优先级队列有报文时优先发送，保证低延迟业务（语音/视频）优先。缺点：高优先级队列持续有流量时，低优先级队列可能"饿死"（永远得不到服务）。2.WRR（Weighted Round Robin，加权轮询）：按权重轮询调度各队列，每个队列获得与权重成比例的带宽，避免饿死。缺点：按报文个数调度，不同报文长度时实际带宽不准，延迟保障不如PQ。3.WFQ（Weighted Fair Queuing，加权公平队列）：按权重和报文长度调度，保证每个流获得公平带宽，按字节调度更精确。4.CBQ（Class Based Queuing，基于类的队列）：结合带宽保证和优先级。5.LPQ（Low Latency Queuing，低延迟队列）：PQ+WFQ/CBQ的结合，一个严格优先级队列（LLQ）保证低延迟，其他队列用WFQ保证公平，是当前主流（既保证语音/视频低延迟，又避免低优先级饿死）。FIFO（先进先出）最简单，无QoS保障，默认队列。QoS模型：Best-Effort（尽力而为，无QoS）、IntServ（集成服务，RSVP信令，每流预留，扩展性差）、DiffServ（区分服务，按类别标记和处理，PHB逐跳行为，扩展性好，当前主流）。DiffServ的PHB：BE（默认尽力而为）、AF（确保转发，4类3丢弃优先级=12种）、EF（加速转发，低延迟低抖动，用于语音）、CS（类别选择，兼容IP优先级）。',
    knowledgeId: 'datacom-qos',
    direction: 'datacom',
  },
  {
    id: 'sec-b005',
    type: 'single',
    question: 'SSL VPN的哪种接入模式不需要安装客户端，浏览器即可访问Web应用？',
    options: ['网络扩展模式', 'Web代理模式', '端口转发模式', '文件共享模式'],
    answer: 'Web代理模式',
    explanation: 'SSL VPN接入模式：1.Web代理（Web Proxy）：无需客户端，浏览器通过HTTPS访问SSL VPN网关，网关代理访问内网Web应用，仅支持Web应用（HTTP/HTTPS），最简单。2.文件共享（File Share）：浏览器访问内网CIFS/FTP文件服务器，仅支持文件访问。3.端口转发（Port Forwarding）：浏览器安装插件，将特定TCP端口的流量通过SSL隧道转发，支持特定TCP应用（如远程桌面、SSH），需浏览器插件。4.网络扩展（Network Extension，全网互联）：安装专用客户端软件（如SecoClient），获得虚拟IP，像在内网一样访问所有IP层应用，功能最强大，类似IPSec VPN。SSL VPN优势：无需客户端（Web代理模式）、穿越NAT/防火墙方便（443端口）、细粒度访问控制、终端安全检查、适合移动办公。SSL VPN与IPSec VPN对比：IPSec VPN适合站点到站点（Site-to-Site），网络层全通，性能高，需配置感兴趣流；SSL VPN适合远程用户接入（Client-to-Site），应用层细粒度控制，易用性好。企业通常两者结合：站点间用IPSec，远程用户用SSL VPN。',
    knowledgeId: 'security-ssl-vpn',
    direction: 'security',
  },
  {
    id: 'wlan-b003',
    type: 'single',
    question: 'WPA2-PSK认证中，四次握手（4-Way Handshake）的目的是？',
    options: ['协商加密算法', '验证PSK并生成PTK（成对临时密钥）', '分配IP地址', '选择信道'],
    answer: '验证PSK并生成PTK（成对临时密钥）',
    explanation: 'WPA2-PSK（预共享密钥）认证过程：1.客户端关联AP后，进行四次握手（4-Way Handshake）。2.第一次握手：AP发送ANonce（AP随机数）给客户端。3.第二次握手：客户端生成SNonce（客户端随机数），用PMK（Pairwise Master Key，由PSK+SSID通过PBKDF2派生）、ANonce、SNonce、AP MAC、客户端MAC计算PTK（Pairwise Transient Key，成对临时密钥），发送SNonce和MIC（消息完整性校验）给AP。4.第三次握手：AP用同样参数计算PTK，验证MIC通过后，发送加密后的GTK（Group Temporal Key，组播临时密钥，用于加密广播/组播流量）给客户端。5.第四次握手：客户端确认收到GTK，安装密钥。四次握手的目的：验证双方都拥有正确的PSK（通过MIC验证），同时生成PTK（用于单播数据加密）和GTK（用于组播数据加密），PSK本身不在空中传输。WPA2使用CCMP（AES-CCM）加密，替代WPA的TKIP（RC4，已不安全）。WPA3使用SAE（Simultaneous Authentication of Equals，对等同时认证）替代PSK四次握手，抵抗离线字典攻击，安全性更高。802.1X（企业级WPA/WPA2/WPA3-Enterprise）使用RADIUS服务器认证，每个用户独立密钥，安全性更高，适合企业。',
    knowledgeId: 'wlan-security',
    direction: 'wlan',
  },
  {
    id: 'dcn-b003',
    type: 'single',
    question: 'EVPN中，Type 2路由（MAC/IP Advertisement）的主要作用是？',
    options: ['选举DF（指定转发器）', '同步主机MAC和IP地址，实现控制面MAC学习', '发现VTEP和头端复制列表', '通告IP前缀路由'],
    answer: '同步主机MAC和IP地址，实现控制面MAC学习',
    explanation: 'EVPN（Ethernet VPN，以太网VPN）路由类型：1.Type 1（Ethernet Auto-Discovery Route，ES自动发现路由）：多归接入场景下发现以太网段（ES）成员，快速收敛。2.Type 2（MAC/IP Advertisement Route，MAC/IP地址通告路由）：同步主机的MAC地址和IP地址，实现控制面MAC学习（无需数据面泛洪），用于ARP代理/抑制、分布式网关主机路由同步。3.Type 3（Inclusive Multicast Ethernet Tag Route，包含组播以太网标签路由）：发现同VNI的VTEP，构建头端复制（HER）列表，用于BUM流量转发。4.Type 4（Ethernet Segment Route，以太网段路由）：多归接入场景下选举DF（Designated Forwarder，指定转发器），避免BUM流量重复。5.Type 5（IP Prefix Route，IP前缀路由）：通告IP前缀路由（如外部路由、汇聚路由），用于分布式网关和跨子网路由。EVPN是BGP的一个地址族（L2VPN EVPN），作为VXLAN的控制面，替代传统的VXLAN数据面学习（泛洪+学习），实现自动化、可扩展、快速收敛。EVPN+VXLAN是数据中心overlay网络的标准架构，支持大二层、多租户、虚拟机迁移、分布式网关等。',
    knowledgeId: 'dcn-evpn',
    direction: 'dcn',
  },
  {
    id: 'dc-b008',
    type: 'judge',
    question: 'NAT中，PAT（端口地址转换）可以让多个内网主机共享一个公网IP地址，通过不同端口号区分。',
    options: ['正确', '错误'],
    answer: '正确',
    explanation: 'NAT（Network Address Translation，网络地址转换）类型：1.静态NAT（Static NAT）：一对一固定映射，内网IP与公网IP一一对应，不节省公网IP，主要用于服务器对外发布（内网服务器映射到公网IP）。2.动态NAT（Dynamic NAT）：多对多，从公网地址池中动态分配，内网主机数不超过公网IP数时可用，仍需较多公网IP。3.PAT（Port Address Translation，端口地址转换，也叫NAPT，Network Address Port Translation）：多对一，多个内网主机共享一个（或少量）公网IP地址，通过不同的源端口号区分不同主机的会话，大幅节省公网IP。PAT是最常用的NAT方式（家庭路由器、企业出口都用PAT）。NAT的作用：1.解决IPv4地址不足（内网用私有IP，通过NAT访问公网）。2.隐藏内网拓扑（提高安全性，外网无法直接访问内网主机）。3.网络迁移时保持内部地址不变。NAT的限制：1.破坏端到端模型（外网无法主动访问内网主机，需静态NAT/端口映射）。2.部分应用不兼容（如FTP、SIP等在载荷中携带IP/端口的应用，需ALG应用层网关）。3.影响IPSec（AH不兼容NAT，ESP可用NAT-T穿越）。4.增加延迟和单点故障。NAT会话表：记录内网IP:端口→公网IP:端口的映射，超时后删除。华为防火墙NAT类型：源NAT（No-PAT、PAT、Smart NAT、三元组NAT）、目的NAT（静态NAT、端口映射）、双向NAT、NAT Server（服务器映射）、Twice NAT（两次转换，源和目的都转换）。',
    knowledgeId: 'datacom-nat',
    direction: 'datacom',
  },
  {
    id: 'sec-b006',
    type: 'single',
    question: 'PKI（公钥基础设施）中，CA（证书颁发机构）的核心作用是？',
    options: ['加密用户数据', '签发和管理数字证书，证明公钥与身份的绑定关系', '存储用户密码', '过滤网络流量'],
    answer: '签发和管理数字证书，证明公钥与身份的绑定关系',
    explanation: 'PKI（Public Key Infrastructure，公钥基础设施）是基于非对称加密的安全基础设施，核心是CA（Certificate Authority，证书颁发机构）。CA的作用：1.签发数字证书（Digital Certificate）：将用户/设备的公钥与其身份（姓名、组织、域名等）绑定，用CA的私钥签名，证明公钥的合法性。2.管理证书生命周期：签发、更新、撤销（CRL证书撤销列表/OCSP在线证书状态协议）、归档。3.维护信任根：CA的公钥（根证书）预先安装在终端/浏览器中，作为信任锚点。数字证书格式：X.509标准，包含版本、序列号、签名算法、颁发者、有效期、主体（Subject）、主体公钥、颁发者唯一标识符、主体唯一标识符、扩展、签名等。证书验证过程：1.验证证书签名（用CA公钥验证CA签名，确保证书未被篡改）。2.验证证书有效期（当前时间在有效期内）。3.验证证书是否被撤销（检查CRL或OCSP）。4.验证证书用途（密钥用法是否匹配）。5.验证证书链（从终端证书到根证书，逐级验证）。PKI应用：HTTPS/TLS（服务器证书+可选客户端证书）、IPSec（数字证书认证）、802.1X（EAP-TLS）、代码签名、电子邮件加密（S/MIME）、VPN、电子签名等。国密PKI：使用SM2（非对称）、SM3（哈希）、SM4（对称）算法，符合中国密码法要求。',
    knowledgeId: 'security-pki',
    direction: 'security',
  },
  {
    id: 'wlan-b004',
    type: 'single',
    question: 'WLAN漫游中，以下哪种漫游需要重新进行802.1X认证？',
    options: ['同一AC内的二层漫游', '同一AC内的三层漫游', '跨AC漫游（无802.11r）', '802.11r快速漫游'],
    answer: '跨AC漫游（无802.11r）',
    explanation: 'WLAN漫游分类：1.同一AC内漫游（Intra-AC Roaming）：终端在同一AC管理的不同AP之间漫游，AC维护终端上下文，无需重新认证，只需重新关联和密钥协商，快速切换。分为二层漫游（同VLAN，IP不变，业务不中断）和三层漫游（不同VLAN/子网，IP可能变化，需隧道转发保证业务不中断）。2.跨AC漫游（Inter-AC Roaming）：终端在不同AC管理的AP之间漫游，AC之间通过漫游隧道同步终端上下文。无802.11r时，需要重新进行802.1X认证（如果是企业级认证）和四次握手，耗时较长（数百毫秒到1秒），可能导致业务中断。有802.11r（快速BSS切换）时，通过预认证和FT密钥层次，无需重新完整认证，实现毫秒级切换。3.802.11r快速漫游（Fast BSS Transition）：通过PMK-R0/R1密钥层次和FT协议，漫游时只需2次消息交换，无需重新802.1X认证，实现<50ms快速切换，适合VoWiFi等实时业务。802.11k（无线资源测量，帮助终端快速发现邻居AP）和802.11v（BSS过渡管理，AC指导终端漫游）配合802.11r，实现智能快速漫游（802.11k/v/r）。漫游的关键：业务不中断（IP不变、会话保持）、切换时间短（<150ms语音不中断，<50ms理想）、安全不降级（重新认证或密钥协商）。华为AC支持敏捷分布式漫游、智能漫游（主动引导终端漫游到更优AP）、频谱导航（引导双频终端到5GHz）等。',
    knowledgeId: 'wlan-roaming',
    direction: 'wlan',
  },
  {
    id: 'dcn-b004',
    type: 'judge',
    question: 'SDN（软件定义网络）的核心思想是控制平面与数据平面分离，通过集中控制器统一管理网络。',
    options: ['正确', '错误'],
    answer: '正确',
    explanation: 'SDN（Software Defined Network，软件定义网络）核心思想：1.控制平面与数据平面分离（Control/Data Plane Separation）：传统网络设备（交换机/路由器）的控制平面（路由计算、协议处理）和数据平面（报文转发）都在设备上，分布式控制。SDN将控制平面抽离到集中的控制器（Controller），数据平面留在交换机上（只负责转发，通过流表规则）。2.集中控制（Centralized Control）：控制器全局掌握网络拓扑和状态，统一计算和下发转发规则，实现全局优化和快速收敛。3.开放接口（Open API）：控制器与交换机之间通过标准协议（如OpenFlow）通信，控制器向上提供API（如REST API），应用可通过API编程控制网络，实现网络自动化和可编程。4.网络可编程（Network Programmability）：网络行为可通过软件编程定义，无需手动配置每台设备，实现自动化部署、灵活调度、快速创新。SDN架构：应用层（Application，网络应用如负载均衡、防火墙、流量工程）→控制层（Controller，SDN控制器如ODL、ONOS、华为iMaster NCE）→基础设施层（Infrastructure，SDN交换机/路由器，支持OpenFlow或NETCONF）。SDN优势：集中管理、自动化部署、灵活调度、快速创新、降低运维成本。SDN应用：数据中心网络（SDN+VXLAN/EVPN）、运营商网络（SD-WAN、核心网）、校园网、云网络等。SDN与传统网络对比：传统网络分布式控制、设备配置为主、收敛慢、扩展性受协议限制；SDN集中控制、软件编程、全局优化、快速收敛。注意：SDN不是要完全替代传统网络，而是在特定场景（数据中心、云、大规模自动化）中发挥优势，很多网络是混合模式（传统+SDN）。',
    knowledgeId: 'dcn-sdn-basic',
    direction: 'dcn',
  },
'''

idx = content.rfind(']')
new_content = content[:idx] + questions + '\n' + content[idx:]

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(new_content)

count = new_content.count("question: '")
print(f"Inserted batch B, total questions: {count}")
