import re

filepath = r"C:\Users\34598\Doubao\chats\2026-08-31\new-chat\ict-prep-app\src\data\quizzes.ts"

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

questions = '''
  { id: 'dc-161', type: 'single', question: 'OSPF中，Totally NSSA区域不接收以下哪种LSA？', options: ['Type 1 和 Type 2', 'Type 3（除默认路由外）、Type 4、Type 5', 'Type 7', '仅Type 5'], answer: 'Type 3（除默认路由外）、Type 4、Type 5', explanation: 'Totally NSSA（完全非纯末梢区域）是NSSA的更严格版本，不接收：Type 3 Summary LSA（除ABR生成的默认路由0.0.0.0/0外）、Type 4 Summary LSA（ASBR位置）、Type 5 AS External LSA。允许Type 7 NSSA External LSA（本区域内引入的外部路由），到ABR后转换为Type 5。NSSA区域不接收Type 4和Type 5，但接收Type 3区域间路由和Type 7。Stub区域不接收Type 4和Type 5，接收Type 3。Totally Stub不接收Type 3（除默认外）、Type 4、Type 5。四种末梢区域对比：Stub（拒绝Type4/5，允许Type3/1/2）、Totally Stub（拒绝Type3除默认/Type4/5，允许默认Type3/1/2）、NSSA（拒绝Type4/5，允许Type3/Type7/1/2）、Totally NSSA（拒绝Type3除默认/Type4/5，允许默认Type3/Type7/1/2）。末梢区域的作用是减少LSA数量和路由表规模，提高稳定性，适用于末节区域（只有一个出口的区域）。', knowledgeId: 'datacom-ospf', direction: 'datacom' },
  { id: 'dc-162', type: 'single', question: 'BGP中，路由反射器（RR）的Cluster_List属性作用是？', options: ['防止路由在RR之间循环', '选择最优路由', '标记路由优先级', '加密路由'], answer: '防止路由在RR之间循环', explanation: 'BGP路由反射器（RR）的防环机制有两个属性：1.Originator_ID（发起者ID，可选非过渡属性）：RR反射路由时，将原始发起者（Originator，最初引入该路由的IBGP邻居）的Router ID添加到Originator_ID属性。当原始发起者收到包含自己Router ID的Originator_ID的路由时，丢弃该路由，防止环路。2.Cluster_List（簇列表，可选非过渡属性）：RR反射路由时，将自己的Cluster ID（簇ID，默认是RR的Router ID，可手动配置）添加到Cluster_List属性的开头。当RR收到包含自己Cluster ID的Cluster_List的路由时，丢弃该路由，防止路由在RR簇之间循环。Cluster_List是一系列Cluster ID的列表，记录路由经过的RR簇。Originator_ID防止路由回到原始发起者，Cluster_List防止路由在RR之间循环。两者配合确保IBGP路由反射无环路。RR的反射规则：从客户端学到的路由反射给所有客户端和非客户端；从非客户端学到的路由仅反射给客户端；从EBGP学到的路由发给所有客户端和非客户端。RR解决了IBGP全互联（Full Mesh）的问题，减少IBGP邻居数量，提高可扩展性。多个RR可组成簇（Cluster），相同Cluster ID，提供冗余备份。RR可层级部署（RR的RR），适用于大规模网络。', knowledgeId: 'datacom-bgp', direction: 'datacom' },
  { id: 'dc-163', type: 'judge', question: 'IS-IS中，DIS（指定中间系统）负责生成伪节点（Pseudonode）LSA。', options: ['正确', '错误'], answer: '正确', explanation: 'IS-IS中，在广播网络（Broadcast Network）中选举DIS（Designated IS，指定中间系统），DIS负责生成伪节点（Pseudonode）LSP（Link State PDU，链路状态协议数据单元）。伪节点是DIS创建的虚拟节点，用于简化广播网络的链路状态描述：1.如果没有伪节点，广播网络中每台路由器都需要与其他所有路由器建立邻接关系并描述链路，LSA数量大（n台路由器需要n*(n-1)条链路描述）。2.有了伪节点，所有连接到该广播网络的路由器都只与伪节点建立邻接关系，描述到伪节点的链路，伪节点描述到所有路由器的链路，大大减少LSA数量（n台路由器只需要n条到伪节点的链路+1条伪节点到所有路由器的链路）。伪节点的System ID由DIS的System ID+一个字节的伪节点ID（Pseudonode ID，通常为01）组成，如DIS System ID为0000.0000.0001，伪节点System ID为0000.0000.0001.01。DIS还负责周期性发送CSNP（Complete Sequence Number PDU，完全序列号报文），用于数据库同步（DIS每10秒发送一次CSNP，包含本地LSDB中所有LSP的摘要，其他路由器对比后发现缺失的LSP则发送PSNP请求）。DIS选举基于接口优先级（默认64，值大者优先，优先级0也参与选举）和System ID（优先级相同时大者优先），DIS可抢占（新加入的高优先级路由器会抢占成为DIS）。IS-IS没有BDR（备份指定路由器），DIS故障后需要重新选举。这与OSPF不同：OSPF有DR和BDR，DR不可抢占，BDR在DR故障后立即成为DR。', knowledgeId: 'datacom-isis', direction: 'datacom' },
  { id: 'dc-164', type: 'single', question: 'MSTP中，CST（公共生成树）的作用是？', options: ['MST域内的生成树', '连接不同MST域，在域间形成一棵公共生成树', '每个MSTI的生成树', '根桥的生成树'], answer: '连接不同MST域，在域间形成一棵公共生成树', explanation: 'MSTP（Multiple Spanning Tree Protocol，多生成树协议，802.1s）的生成树分为：1.MSTI（Multiple Spanning Tree Instance，多生成树实例）：MST域内的生成树实例，每个MSTI独立计算生成树，可映射不同VLAN，实现VLAN负载分担。MSTI仅在MST域内有效，不跨域。2.CST（Common Spanning Tree，公共生成树）：在整个交换网络（包括不同MST域和STP/RSTP域）中形成的一棵公共生成树，用于连接不同MST域，确保域间无环路。CST将每个MST域视为一个逻辑交换机（虚拟桥），域间运行CST。3.CIST（Common and Internal Spanning Tree，公共和内部生成树）：CIST = CST（域间公共生成树）+ IST（Internal Spanning Tree，域内内部生成树，MSTI 0）。CIST是整个网络的总生成树，确保整个网络无环路。MSTP的工作原理：MST域内运行MSTP，多个MSTI实现负载分担；MST域对外表现为一个虚拟桥，参与CST计算，与其他MST域或STP/RSTP域互通。MST域的判定条件：域名（Configuration Name）、修订级别（Revision Level）、VLAN-实例映射关系（VLAN-to-instance Mapping）三者完全相同。MSTP兼容STP和RSTP：MSTP域与STP/RSTP设备互联时，MSTP端口会发送STP/RSTP BPDU（或MSTP BPDU，STP设备将MSTP BPDU视为RSTP BPDU），实现互通。MSTP的优势：兼容STP/RSTP、支持多实例负载分担、减少VLAN场景下的端口阻塞、提高链路利用率，是企业网络的主流生成树协议。', knowledgeId: 'datacom-stp', direction: 'datacom' },
  { id: 'dc-165', type: 'single', question: 'VXLAN中，VNI（VXLAN网络标识符）的位数和支持的网段数量是？', options: ['12位，4094个', '16位，65536个', '24位，约1600万个', '32位，约40亿个'], answer: '24位，约1600万个', explanation: 'VXLAN（Virtual Extensible LAN，虚拟可扩展局域网，RFC 7348）中，VNI（VXLAN Network Identifier，VXLAN网络标识符）占24位，支持约1600万个VXLAN网段（2^24 = 16,777,216），远多于VLAN的4094个（VLAN ID占12位，2^12=4096，可用1-4094）。VNI的作用：1.标识一个VXLAN网段（类似VLAN ID标识VLAN），不同VNI之间二层隔离。2.在VXLAN封装头中携带VNI，对端VTEP根据VNI确定目标VXLAN网段。3.解决VLAN数量不足的问题，满足云计算和多租户数据中心的需求（大量租户需要隔离的二层网络）。VXLAN封装格式：外层以太网头（14字节）+外层IP头（20字节，源/目的VTEP IP）+外层UDP头（8字节，目的端口4789，源端口哈希用于ECMP负载分担）+VXLAN头（8字节，Flags 1字节+Reserved 3字节+VNI 3字节+Reserved 1字节）+原始以太网帧（14字节+载荷+FCS 4字节）。VXLAN头8字节中，VNI占24位（3字节），Flags中I位（第8位）设为1表示VNI有效。VXLAN通过MAC-in-UDP封装，在三层IP网络（underlay）上构建大二层虚拟网络（overlay），解决：1.VLAN数量不足（4094限制）2.大二层扩展（STP无法支撑大规模二层，VXLAN基于三层underlay，可利用ECMP多路径）3.虚拟机迁移（IP不变，大二层域内任意迁移）4.多租户隔离（不同VNI隔离）。VXLAN是当前数据中心网络overlay的主流技术，通常与EVPN（控制面）配合使用（IP Fabric + EVPN/VXLAN）。', knowledgeId: 'dcn-vxlan-basic', direction: 'dcn' },
  { id: 'sec-119', type: 'single', question: 'IPSec中，IKE SA的默认生命周期是？', options: ['3600秒（1小时）', '86400秒（24小时）', '1800秒（30分钟）', '604800秒（7天）'], answer: '86400秒（24小时）', explanation: 'IKE SA（Internet Key Exchange Security Association，IKE安全联盟）的默认生命周期通常是86400秒（24小时），IPSec SA的默认生命周期通常是3600秒（1小时）或按流量计算（如10GB）。IKE SA用于保护IKE协商（阶段二的协商），一个IKE SA可用于建立多个IPSec SA。IPSec SA用于保护用户数据（加密/认证），每个方向一个（inbound和outbound）。生命周期到期前会自动重新协商（rekey），确保密钥定期更新，提高安全性。IKE SA生命周期可通过ike sa duration命令修改（范围通常180-604800秒），IPSec SA生命周期可通过ipsec sa duration命令修改（时间或流量）。IKEv1阶段一（建立IKE SA）模式：主模式（Main Mode，6条消息，保护身份）和野蛮模式（Aggressive Mode，3条消息，不保护身份）。阶段二（建立IPSec SA）：快速模式（Quick Mode，3条消息）。IKEv2简化为4条消息（IKE_SA_INIT 2条+IKE_AUTH 2条），同时建立IKE SA和第一个IPSec SA，更安全高效，支持MOBIKE（移动性，IP地址变化时保持连接）。IKE协商参数：加密算法（DES/3DES/AES/SM4）、认证算法（MD5/SHA1/SHA2/SM3）、认证方式（预共享密钥PSK/数字证书RSA-Signature）、DH组（Diffie-Hellman，1/2/5/14/19/20/21等，用于密钥交换）、生命周期。两端IKE参数必须匹配才能协商成功。IPSec安全协议：AH（协议号51，仅认证，不加密，不支持NAT）和ESP（协议号50，加密+认证，主流）。工作模式：传输模式（主机到主机，原IP头不变）和隧道模式（网关到网关，新增外部IP头，VPN常用）。', knowledgeId: 'security-ipsec', direction: 'security' },
  { id: 'wlan-111', type: 'single', question: 'WLAN中，802.11r（快速BSS切换）的主要作用是？', options: ['加密数据', '减少漫游时认证时间，实现毫秒级快速切换', '调整发射功率', '选择信道'], answer: '减少漫游时认证时间，实现毫秒级快速切换', explanation: '802.11r（Fast BSS Transition，快速BSS切换，也叫FT）是WLAN漫游优化标准，主要作用是减少漫游时的认证和密钥协商时间，实现毫秒级快速切换，避免语音/视频等实时业务中断。传统漫游（无802.11r）：终端漫游到新AP时，需要重新进行完整的802.1X认证（如果是企业级WPA/WPA2）和4次握手（4-Way Handshake），耗时数百毫秒到1秒，可能导致语音通话中断或视频卡顿。802.11r的优化：1.预认证（Pre-authentication）：终端在漫游前，通过当前AP与目标AP预认证，获取目标AP的PMK（Pairwise Master Key）。2.FT密钥层次：使用PMK-R0（R0密钥，由AC/认证服务器生成）和PMK-R1（R1密钥，由R0派生，存储在目标AP），漫游时终端与目标AP直接使用R1密钥协商PTK（Pairwise Transient Key），无需重新完整认证。3.快速切换：漫游时只需2次消息交换（FT协议），而非完整的802.1X认证+4次握手，实现毫秒级（通常<50ms）切换。802.11r与802.11k（Radio Resource Measurement，无线资源测量，帮助终端快速发现邻居AP，减少扫描时间）和802.11v（BSS Transition Management，BSS过渡管理，AC/AP指导终端漫游到更优AP，实现负载均衡和优化覆盖）配合（合称802.11k/v/r），实现智能快速漫游，是企业WLAN的重要功能，特别适合VoWiFi（Voice over WiFi）、视频会议等实时业务。802.11r需要AP和终端都支持才能生效（大多数现代智能手机和笔记本支持）。802.11r有两种模式：Over-the-DS（通过分布式系统，通过当前AP与目标AP通信，预认证）和Over-the-Air（直接与目标AP通信，直接认证）。Over-the-DS更常用，因为不需要终端离开当前AP信道去与目标AP通信。', knowledgeId: 'wlan-roaming', direction: 'wlan' },
  { id: 'dcn-109', type: 'judge', question: '数据中心Spine-Leaf架构中，任意两台服务器之间的通信都经过2跳（Leaf→Spine→Leaf）。', options: ['正确', '错误'], answer: '正确', explanation: 'Spine-Leaf（叶脊）架构中，所有Leaf（叶节点，接入交换机，连接服务器）都连接到所有Spine（脊节点，核心交换机，不连接服务器），形成Full Mesh（全互联）拓扑。任意两台服务器之间的通信路径：服务器→Leaf（源Leaf）→Spine（任意一个Spine）→Leaf（目的Leaf）→服务器，在网络设备层面经过2跳（Leaf→Spine→Leaf），延迟低且可预测（无论哪两台服务器通信都是2跳，不会因为位置不同而延迟不同）。这是Spine-Leaf相比传统三层架构（核心-汇聚-接入）的重要优势：传统三层架构中，同一汇聚下的服务器通信2跳（接入→汇聚→接入），跨汇聚的服务器通信3跳（接入→汇聚→核心→汇聚→接入），延迟不一致，核心层可能成为瓶颈。Spine-Leaf的2跳一致性和无阻塞特性（通过ECMP等价多路径负载分担，充分利用所有Spine链路带宽）使其非常适合数据中心东西向流量（East-West Traffic，服务器之间通信，占数据中心流量70-80%以上，如分布式计算、存储访问、虚拟机迁移、微服务通信等）。Spine-Leaf的水平扩展（Horizontal Scaling）：1.增加Leaf：增加接入端口密度（连接更多服务器）。2.增加Spine：增加东西向带宽（更多Spine链路，ECMP更多路径）。3.任意扩展不影响现有拓扑，无需重新设计。Spine-Leaf的Clos架构渊源：Spine-Leaf是三级Clos架构的简化（Leaf=接入级，Spine=中间级），严格无阻塞（Strictly Non-blocking），大规模数据中心可采用多级Clos（如五级、七级）。Spine-Leaf的underlay（底层网络）通常运行BGP（eBGP或iBGP）或OSPF/IS-IS，提供ECMP多路径和高可靠；overlay（叠加网络）通常使用VXLAN/EVPN，实现大二层和多租户。Spine-Leaf是当前数据中心网络的标准架构，被AWS、Azure、Google、Facebook等大型云厂商广泛采用。', knowledgeId: 'dcn-arch', direction: 'dcn' },
'''

pattern = r'\n  // ==================== 自动更新题库 Batch 1'
replacement = questions + '\n  // ==================== 自动更新题库 Batch 1'

new_content, count = re.subn(pattern, replacement, content, count=1)

if count > 0:
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Inserted {questions.count('id:')} questions successfully")
else:
    print("Pattern not found!")
