import re

filepath = r"C:\Users\34598\Doubao\chats\2026-08-31\new-chat\ict-prep-app\src\data\quizzes.ts"

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

questions = '''
  { id: 'dc-151', type: 'single', question: 'OSPF中，ABR生成的Type 3 Summary LSA用于描述什么？', options: ['本区域内的路由器链路状态', '广播网络信息', '区域间的路由信息', '外部路由信息'], answer: '区域间的路由信息', explanation: 'OSPF LSA类型：1.Type 1 Router LSA：每台路由器生成，描述本路由器的链路状态（接口、开销、邻居等），仅在本区域内泛洪。2.Type 2 Network LSA：DR生成，描述广播/NBMA网络中所有连接的路由器，仅在本区域内泛洪。3.Type 3 Summary LSA（网络汇总LSA）：ABR生成，描述区域间的路由信息（将本区域的Type 1/2汇总为Type 3发布到其他区域，或将其他区域的Type 3汇总后发布到本区域），可跨区域传播。4.Type 4 Summary LSA（ASBR汇总LSA）：ABR生成，描述ASBR的位置（ASBR的Router ID和到达ASBR的路径），用于让其他区域的路由器知道如何到达ASBR。5.Type 5 AS External LSA：ASBR生成，描述外部路由（引入的其他协议路由），在整个OSPF域（除Stub/Totally Stub/NSSA）泛洪。6.Type 7 NSSA External LSA：NSSA区域的ASBR生成，描述外部路由，仅在NSSA区域内泛洪，到ABR后转换为Type 5。Type 3 LSA是区域间路由的载体，ABR通过Type 3将一个区域的路由信息发布到其他区域，实现区域间路由。Stub区域不接收Type 5但接收Type 3，Totally Stub区域只接收Type 3默认路由。', knowledgeId: 'datacom-ospf', direction: 'datacom' },
  { id: 'dc-152', type: 'single', question: 'BGP中，以下哪个属性是可选过渡（Optional Transitive）的？', options: ['Origin', 'AS_Path', 'Next_Hop', 'Community'], answer: 'Community', explanation: 'BGP属性分类：1.公认必遵（Well-known Mandatory）：所有BGP路由器都必须识别，每条更新必须包含。包括Origin、AS_Path、Next_Hop。2.公认自由决定（Well-known Discretionary）：所有BGP路由器都能识别，但不一定每条更新都包含，可选择是否使用。包括Local_Pref、Atomic_Aggregate。3.可选过渡（Optional Transitive）：不要求所有路由器都识别，但如果不识别，应原样传递给其他邻居（可过渡）。包括Community、Aggregator。4.可选非过渡（Optional Non-transitive）：不要求所有路由器识别，如果不识别，可忽略不传递。包括MED、Originator_ID、Cluster_List、MP_REACH_NLRI等。Community（团体属性）是可选过渡属性，用于标记一组路由，便于策略控制（如根据Community设置Local_Pref、MED等），Community值32位，分为公认团体（No_Export、No_Advertise、Internet、Local_AS）和私有团体（AS:NN格式）。Community可跨AS传递（可选过渡），也可配置不传递（如No_Export只在本AS内传播）。MED是可选非过渡属性，默认不跨AS传递（只在相邻AS间有效，除非配置always-compare-med或compare-med）。', knowledgeId: 'datacom-bgp', direction: 'datacom' },
  { id: 'dc-153', type: 'judge', question: 'IS-IS的Level-1路由器访问其他区域时，通过本区域的Level-1-2路由器转发，类似OSPF的默认路由。', options: ['正确', '错误'], answer: '正确', explanation: 'IS-IS的Level-1路由器（L1）只能与同区域的L1/L1-2建立邻居，维护Level-1链路状态数据库，只知道本区域内的拓扑，不知道其他区域的具体路由。当L1路由器需要访问其他区域（或外部网络）时，通过本区域的Level-1-2路由器（L1/2）转发：L1/2路由器会在Level-1 LSP中设置ATT（Attachment，附着位），通知L1路由器"我连接到骨干（Level-2），可以通过我访问其他区域"。L1路由器收到设置了ATT位的LSP后，会生成一条指向最近的L1/2路由器的默认路由（类似OSPF Stub区域的默认路由），将访问其他区域的流量发给L1/2路由器。L1/2路由器同时维护Level-1和Level-2数据库，知道其他区域的路由，负责将L1区域的路由发布到Level-2骨干，将Level-2骨干的路由（或默认路由）发布到L1区域。这与OSPF的Stub区域类似：Stub区域的ABR向Stub区域发布默认路由（Type 3），Stub区域内的路由器通过ABR访问外部。IS-IS的ATT位机制更简单（不需要额外的LSA，只需在LSP中设置一位）。路由渗透（Route Leakage）：L1/2路由器可以将Level-2的具体路由（而非仅默认路由）发布到L1区域，解决次优路径问题（L1路由器可能选择不是最优的L1/2路由器）。', knowledgeId: 'datacom-isis', direction: 'datacom' },
  { id: 'dc-154', type: 'single', question: 'RSTP的P/A（Proposal/Agreement）协商机制的作用是？', options: ['快速选举根桥', '实现端口快速进入Forwarding状态，无需等待30秒', '加密BPDU', '选择指定端口'], answer: '实现端口快速进入Forwarding状态，无需等待30秒', explanation: 'RSTP（802.1w）的P/A（Proposal/Agreement，提议/同意）协商机制是实现快速收敛的核心：1.当链路up或指定端口角色变化时，指定端口（Designated Port）发送Proposal BPDU（提议自己成为指定端口，并请求快速进入Forwarding）。2.对端端口收到Proposal后，进行同步（Sync）：阻塞所有其他边缘端口以外的端口（确保无环路），然后回复Agreement BPDU（同意）。3.指定端口收到Agreement后，立即进入Forwarding状态（无需等待Listening+Learning的30秒Forward Delay）。4.对端端口（根端口或替代端口）也同步进入Forwarding状态。P/A机制是逐链路协商的，在点到点链路（全双工）上有效，实现秒级快速收敛。RSTP快速收敛的其他机制：1.边缘端口（Edge Port）：连接终端，不参与STP，直接进入Forwarding。2.替代端口/备份端口：根端口/指定端口的备份，故障时快速切换。3.更频繁的BPDU发送（Hello Time 2秒，超时3倍=6秒，比STP的20秒Max Age快）。RSTP兼容STP（与STP交换机互操作时退化为STP速度）。MSTP基于RSTP，也使用P/A机制实现快速收敛。', knowledgeId: 'datacom-stp', direction: 'datacom' },
  { id: 'dc-155', type: 'single', question: '三层交换机实现VLAN间路由的接口是？', options: ['物理接口', 'SVI（交换虚拟接口/VLANIF）', '子接口', 'Loopback接口'], answer: 'SVI（交换虚拟接口/VLANIF）', explanation: '三层交换机（Layer 3 Switch）实现VLAN间路由的方式：1.SVI（Switched Virtual Interface，交换虚拟接口，华为称为VLANIF接口）：为每个VLAN创建一个逻辑三层接口，配置该VLAN的网关IP地址，不同VLAN的SVI之间通过三层路由表实现VLAN间通信。SVI是三层交换机的标准VLAN间路由方式，硬件转发（ASIC芯片），性能高。2.物理三层接口：三层交换机的物理接口可配置为三层口（no switchport），配置IP地址，用于连接路由器或其他三层设备，但不用于VLAN间路由（VLAN是二层概念）。3.子接口（Sub-interface）：路由器上的方式（单臂路由），物理接口划分为多个逻辑子接口，每个子接口配置802.1Q封装和网关IP，实现VLAN间路由。三层交换机通常不用子接口（用SVI更高效）。4.Loopback接口：逻辑回环接口，用于路由器ID、管理地址、BGP邻居等，不用于VLAN间路由。三层交换机相比单臂路由的优势：a.硬件转发（ASIC），性能高（线速），路由器子接口是软件转发，性能低。b.每个VLAN独立SVI，带宽独立，单臂路由所有VLAN共享一个物理接口带宽，成为瓶颈。c.配置更简单，可靠性更高。三层交换机是企业网络VLAN间路由的主流方案，SVI是核心技术。', knowledgeId: 'datacom-vlan', direction: 'datacom' },
  { id: 'sec-116', type: 'single', question: '防火墙会话表（Session Table）中，TCP会话的状态不包括以下哪个？', options: ['SYN', 'ESTABLISHED', 'FIN', 'CLOSED'], answer: 'CLOSED', explanation: '防火墙状态检测维护TCP会话状态机，常见状态：1.SYN：收到SYN，等待SYN-ACK（三次握手第一步）。2.SYN-ACK：收到SYN-ACK，等待ACK（三次握手第二步）。3.ESTABLISHED：三次握手完成，会话建立，正常传输数据。4.FIN：收到FIN，等待FIN-ACK（四次挥手第一步）。5.CLOSE-WAIT/LAST-ACK/TIME-WAIT等：TCP连接关闭过程中的状态。CLOSED不是防火墙会话表中的活跃状态（CLOSED表示连接已关闭，会话表项已删除或即将超时删除）。防火墙会话表记录每个会话的五元组（源/目的IP、源/目的端口、协议）、状态、超时时间、安全策略、NAT转换信息、字节数/包数统计等。状态检测的优势：1.只检查首包（匹配安全策略），后续包直接匹配会话表转发，性能高。2.检测应用层协议状态（如FTP动态端口、TCP标志位合法性），防止应用层攻击和异常报文。3.会话超时：不同协议/状态有不同超时时间（TCP ESTABLISHED通常1200秒/20分钟，UDP通常120秒，ICMP通常20秒），超时后删除会话表项。4.会话表项数量是防火墙的重要性能指标（并发连接数）。ASPF（应用层包过滤）进一步检测应用层协议状态，自动开放动态端口（如FTP数据连接）。', knowledgeId: 'security-firewall-basic', direction: 'security' },
  { id: 'sec-117', type: 'single', question: '以下哪个哈希算法已被证明存在碰撞攻击，不推荐用于安全场景？', options: ['SHA-256', 'SHA-3', 'MD5', 'SM3'], answer: 'MD5', explanation: '哈希算法（Hash Algorithm）将任意长度数据映射为固定长度摘要（Digest），用于完整性校验、数字签名、密码存储等。安全性要求：抗碰撞（Collision Resistance，难以找到两个不同输入产生相同哈希）、抗原像（Pre-image Resistance，难以从哈希反推输入）、抗第二原像（Second Pre-image Resistance，给定输入难以找到另一个不同输入产生相同哈希）。已被破解/不推荐的算法：1.MD5（Message Digest 5，128位）：2004年王小云团队证明存在碰撞攻击，2008年实现实际碰撞（伪造SSL证书），已不安全，不推荐用于安全场景（数字签名、证书等），可用于非安全场景（如文件校验、UUID）。2.SHA-1（160位）：2017年Google证明实际碰撞（SHAttered），已不安全，不推荐用于安全场景（TLS证书、数字签名等），NIST已弃用。仍安全/推荐的算法：1.SHA-2（SHA-224/256/384/512）：当前主流，未发现有效碰撞，推荐使用。2.SHA-3（Keccak，224/256/384/512）：最新标准，基于不同的海绵结构，安全性更高。3.SM3（256位）：中国国密哈希算法，安全，国内合规要求。4.BLAKE2/3：高性能安全哈希算法。注意：即使使用安全哈希算法，密码存储也应使用加盐（Salt）和慢哈希算法（bcrypt、scrypt、Argon2），而不是直接用MD5/SHA等快速哈希（易被彩虹表/暴力破解）。', knowledgeId: 'security-crypto', direction: 'security' },
  { id: 'wlan-109', type: 'single', question: 'WLAN中，直接转发（本地转发）与隧道转发（集中转发）的主要区别是？', options: ['直接转发AP直接转发用户数据不经过AC，隧道转发用户数据通过CAPWAP数据隧道到AC转发', '直接转发更安全', '隧道转发性能更高', '直接转发需要AC性能更高'], answer: '直接转发AP直接转发用户数据不经过AC，隧道转发用户数据通过CAPWAP数据隧道到AC转发', explanation: 'WLAN数据转发模式：1.直接转发（Direct Forwarding，也叫本地转发Local Switching）：AP直接将用户数据转发到有线网络（根据VLAN标签转发到对应VLAN），不经过AC，控制报文仍通过CAPWAP控制隧道到AC。优点：a.性能好（数据不经过AC，AC无瓶颈，AP线速转发）b.网络拓扑简单（数据直接进入有线网络）c.AC故障不影响已有用户数据转发（仅影响管理和新用户接入）。缺点：a.安全策略分散（用户数据不经过AC，AC上的安全策略/内容过滤无法直接应用，需在AP或上游设备配置）b.数据加密需在AP上配置（如802.11i加密在AP上完成）。2.隧道转发（Tunnel Forwarding，也叫集中转发Central Switching）：用户数据通过CAPWAP数据隧道（UDP 5247）封装到AC，由AC统一解封装和转发。优点：a.集中控制（所有用户数据经过AC，可统一应用安全策略、QoS、内容过滤、流量统计）b.便于集中管理和审计。缺点：a.AC可能成为性能瓶颈（所有用户数据经过AC，AC转发能力受限）b.延迟稍高（数据多经过AC一跳）c.AC故障影响所有用户数据转发。直接转发是当前主流（企业WLAN，AC性能通常不足以承载所有用户数据），隧道转发适用于需要集中安全控制或小规模场景。华为AC通过forward-mode命令配置（direct或tunnel），可基于VAP模板配置不同SSID使用不同转发模式。', knowledgeId: 'wlan-arch', direction: 'wlan' },
  { id: 'dcn-107', type: 'single', question: 'EVPN中，Type 2路由（MAC/IP Advertisement）携带的信息不包括？', options: ['主机MAC地址', '主机IP地址', 'VNI和VTEP IP', '加密密钥'], answer: '加密密钥', explanation: 'EVPN Type 2路由（MAC/IP Advertisement Route，MAC/IP地址通告路由）是EVPN最常用的路由类型，用于同步主机的MAC地址和IP地址信息，携带的信息包括：1.MAC地址（主机的二层MAC地址）2.IP地址（主机的三层IP地址，可选，用于分布式网关/ARP代理）3.VNI（VXLAN网络标识符，标识所属VXLAN网段）4.VTEP IP（通告该路由的VTEP的IP地址，下一跳）5.MPLS标签（或VXLAN标签，用于数据转发）6.以太网段标识（ESI，用于多归接入场景）7.路由器MAC（Router MAC，VTEP的MAC地址）等。Type 2路由的作用：1.控制面学习MAC：VTEP通过Type 2路由学习远端主机MAC与VTEP IP的映射，直接安装MAC表项，无需数据面泛洪学习，减少广播流量。2.ARP代理/抑制：VTEP通过Type 2路由学习到主机IP-MAC映射，可直接响应ARP请求，减少ARP广播泛洪。3.分布式网关：Type 2路由携带主机IP，用于分布式网关场景下的主机路由同步（其他VTEP学习到主机IP路由，实现跨子网三层转发）。4.快速收敛：主机移动或故障时，通过Type 2路由撤销（Withdraw）快速更新MAC表，减少黑洞时间。加密密钥不是EVPN路由携带的信息（VXLAN本身不加密，加密需要IPSec等其他技术）。EVPN其他路由类型：Type 1（ES自动发现）、Type 3（VTEP发现/头端复制）、Type 4（DF选举）、Type 5（IP前缀路由）。', knowledgeId: 'dcn-evpn', direction: 'dcn' },
  { id: 'dc-156', type: 'single', question: 'IPv6中，邻居发现协议（NDP）的NS（邻居请求）报文作用是？', options: ['请求路由器地址前缀', '请求目标IP对应的MAC地址（替代IPv4的ARP）', '宣告自己的MAC地址', '检测路由可达性'], answer: '请求目标IP对应的MAC地址（替代IPv4的ARP）', explanation: 'IPv6邻居发现协议（NDP，Neighbor Discovery Protocol，基于ICMPv6）替代了IPv4中的ARP、ICMP路由器发现、重定向等功能，包含5种报文：1.RS（Router Solicitation，路由器请求，ICMPv6类型133）：主机发送，请求路由器发送RA，主机启动或接口up时发送。2.RA（Router Advertisement，路由器通告，类型134）：路由器周期性发送或响应RS，包含地址前缀、前缀长度、默认网关、MTU、跳数限制等，用于SLAAC无状态自动配置。3.NS（Neighbor Solicitation，邻居请求，类型135）：主机发送，请求目标IP地址对应的MAC地址（替代IPv4的ARP请求），目标地址是被请求的IP，源地址是自己的IPv6地址，目的地址是目标IP的请求节点组播地址（Solicited-Node Multicast，FF02::1:FFXX:XXXX）。NS也用于DAD（重复地址检测，源地址为::）和邻居不可达检测（NUD）。4.NA（Neighbor Advertisement，邻居通告，类型136）：响应NS，宣告自己的MAC地址（替代IPv4的ARP响应），也可主动发送（地址变化时）。NA包含目标IP、目标MAC、标志位（Router/Solicited/Override）。5.Redirect（重定向，类型137）：路由器通知主机有更优的下一跳，类似IPv4的ICMP重定向。NDP是IPv6的核心协议，工作在链路本地范围（使用FE80::/10地址），实现地址解析、邻居发现、路由器发现、地址自动配置、重复地址检测、邻居不可达检测等功能。NS报文替代了IPv4的ARP请求，但使用组播（而非广播），更高效。', knowledgeId: 'datacom-ipv6-basic', direction: 'datacom' },
  { id: 'sec-118', type: 'single', question: '802.1X认证中，认证设备（Authenticator）在用户认证通过前，端口允许通过的报文是？', options: ['所有报文', '仅EAPoL报文（802.1X认证报文）', '仅HTTP报文', '仅DHCP报文'], answer: '仅EAPoL报文（802.1X认证报文）', explanation: '802.1X认证中，认证设备（Authenticator，交换机/AP）的端口在用户认证通过前，处于未授权状态（Unauthorized），只允许EAPoL（EAP over LAN，802.1X认证报文，目的MAC 01-80-C2-00-00-03）通过，其他所有报文（如HTTP、DHCP、TCP/IP数据等）都被阻塞，用户无法访问网络资源。认证通过后，端口变为授权状态（Authorized），允许正常流量通过。802.1X的三种接入控制方式（端口控制模式）：1.自动模式（Auto）：默认，端口自动发起802.1X认证，认证通过后开放。2.强制授权模式（Force Authorized）：不进行认证，端口始终允许所有流量通过（相当于关闭802.1X）。3.强制非授权模式（Force Unauthorized）：端口始终拒绝所有流量（始终关闭）。802.1X认证流程：客户端（Supplicant）发送EAPoL-Start→认证设备请求身份（EAP-Request/Identity）→客户端回复身份（EAP-Response/Identity）→认证设备封装为RADIUS Access-Request发给认证服务器→服务器挑战（EAP-Request）→客户端响应→服务器验证通过返回Access-Accept→认证设备发送EAP-Success→端口开放授权→客户端可正常访问网络。Guest VLAN（访客VLAN）：认证失败或无客户端的用户可访问Guest VLAN（有限资源，如Internet），是802.1X的扩展功能。Critical VLAN（关键VLAN）：RADIUS服务器不可达时，用户可访问Critical VLAN，保证基本网络访问。', knowledgeId: 'security-8021x', direction: 'security' },
  { id: 'wlan-110', type: 'judge', question: 'WLAN中，WMM（Wi-Fi多媒体）将语音业务映射到AC_VO（最高优先级）。', options: ['正确', '错误'], answer: '正确', explanation: 'WMM（Wi-Fi Multimedia，Wi-Fi多媒体，基于802.11e）是WLAN QoS的基础，将无线流量分为4个接入类别（Access Category，AC），优先级从高到低：1.AC_VO（Voice，语音）：最高优先级，低延迟、低丢包、低抖动，用于VoWiFi电话、实时语音等。AIFS最小，ECW最小，TXOP最大（可连续发送多个帧）。2.AC_VI（Video，视频）：次高优先级，用于视频会议、流媒体视频、监控视频等。AIFS较小，ECW较小，TXOP较大。3.AC_BE（Best Effort，尽力而为）：默认优先级，用于网页浏览、文件下载、邮件等普通业务。AIFS默认，ECW默认。4.AC_BK（Background，背景）：最低优先级，用于后台下载、软件更新、备份等不敏感业务。AIFS最大，ECW最大，TXOP为0（每次只能发一个帧）。WMM通过不同的AIFS（仲裁帧间间隔，越大等待越久优先级越低）、ECWmin/ECWmax（竞争窗口，越大冲突概率越高优先级越低）、TXOP（传输机会，高优先级可连续发送多个帧）参数实现差异化服务。用户优先级（UP，User Priority，802.1p，0-7）映射到WMM AC：UP 7(NC)/6(VO)→AC_VO，UP 5(VI)/4(CL)→AC_VI，UP 0(BE)/3(EE)→AC_BE，UP 1(BK)/2(保留)→AC_BK。语音业务（VoWiFi）映射到AC_VO，获得最高优先级和最低延迟，是WMM的典型应用。WMM认证是Wi-Fi联盟的认证项目，支持WMM的设备可实现QoS。WMM还支持WMM-PS（WMM Power Save，更高效的省电机制）和U-APSD（Unscheduled Automatic Power Save Delivery，非调度自动省电交付）。', knowledgeId: 'wlan-qos', direction: 'wlan' },
  { id: 'dcn-108', type: 'single', question: 'SD-WAN相比传统MPLS VPN的主要优势不包括？', options: ['智能选路（根据应用质量选择链路）', '可使用Internet链路降低成本', '集中管理和零接触部署', '物理传输距离更短，延迟更低'], answer: '物理传输距离更短，延迟更低', explanation: 'SD-WAN（Software Defined Wide Area Network，软件定义广域网）是基于SDN技术的广域网解决方案，相比传统MPLS VPN的优势：1.智能选路（Application-aware Routing）：根据应用的SLA要求（延迟、丢包、抖动、带宽）和链路质量，动态选择最优链路（关键应用走MPLS/高质量链路，普通应用走Internet），提高用户体验和链路利用率。2.降低成本：可使用廉价的Internet链路（宽带、4G/5G）替代或补充昂贵的MPLS专线，混合链路（Hybrid WAN），降低广域网成本（通常可降低30-50%）。3.集中管理和自动化：云管平台统一配置、监控、运维，零接触部署（ZTP，Zero Touch Provisioning，设备上电自动获取配置），减少运维成本。4.应用优化：应用识别（DPI）、QoS、TCP优化、缓存、压缩等，提升应用体验。5.安全集成：集成防火墙、IPS、URL过滤、加密等安全功能（SASE，Secure Access Service Edge，安全访问服务边缘，将SD-WAN与安全服务融合）。6.灵活扩展：支持多种链路类型（MPLS、Internet、4G/5G、卫星），快速开通新站点。物理传输距离由地理位置决定，SD-WAN不改变物理距离，Internet链路的物理延迟可能高于MPLS（因为MPLS通常有QoS保障和更优路径），但SD-WAN通过智能选路和应用优化保证关键应用体验。SD-WAN不保证延迟更低，而是保证关键应用在可用链路中选择最优路径。SD-WAN是当前企业广域网改造的主流方案，特别适合多分支、云应用多、需要灵活接入的企业。', knowledgeId: 'dcn-sdn-basic', direction: 'dcn' },
'''

pattern = r'\n  // ==================== 自动更新题库 Batch 1'
replacement = questions + '\n  // ==================== 自动更新题库 Batch 1'

new_content, count = re.subn(pattern, replacement, content, count=1)

if count > 0:
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Inserted {questions.count('id:')} questions successfully")
else:
    print("Pattern not found!")
